---
title: "umap_analysis"
format: html
editor: source
---

# Set-up

```{r setup, message = FALSE, warning = FALSE, results = 'hide'}
library(HDAnalyzeR)
library(tidyverse)
```

# Import data & metadata

```{r, message = FALSE, results = 'hide'}
data_scapis <- hd_import_data("data/processed_data/scapis_preprocessed.csv")
data_igt <- hd_import_data("data/processed_data/igt_preprocessed.csv")
metadata_scapis <- hd_import_data("data/processed_data/metadata_scapis.csv")
metadata_igt <- hd_import_data("data/processed_data/metadata_igt.csv")

obj_scapis <- hd_initialize(data_scapis, metadata_scapis, is_wide = TRUE)
obj_igt <- hd_initialize(data_igt, metadata_igt, is_wide = TRUE)
```

```{r}
disease_vec <- c("Obesity", "T2D", "MS", "MASLD", "Carotid_plaque", "CAC")
```

```{r}
disease_palette <- c("Obesity" = "#E7662B",
                     "T2D" = "#321433",
                     "MS" = "#08585A", 
                     "MASLD" = "#FFD321", 
                     "Carotid_plaque" = "#E8A29A", 
                     "CAC" = "#9E0142")
```

# Import LASSO model features

```{r, message = FALSE, results = 'hide'}
lasso_features <- readRDS("results/models_results/lasso_features.RData")
lasso_features_de <- readRDS("results/models_results/lasso_features_de.RData")
glucosegroup_model_results <- readRDS("results/models/lasso_glucosegroups_multiclass.RData")

obj_igt_filtered <- hd_initialize(data_igt |> select(DAid, all_of(lasso_features_de |> pull(Feature) |> unique())), metadata_igt, is_wide = TRUE)
```

# UMAP

## Sex, Age & BMI

There is no separation with most the parameters. There might be a small separation with BMI/Obesity.

Check for sex, age and BMI effects.

```{r}
hd_auto_umap(obj_igt, plot_color = "Sex", plot_palette = "sex")[["umap_plot"]]

hd_auto_umap(obj_igt, plot_color = "Age")[["umap_plot"]]

hd_auto_umap(obj_igt, plot_color = "BMI")[["umap_plot"]]
```

## All features vs protein panel

### T2D

```{r}
hd_auto_umap(obj_igt, plot_color = "T2D", plot_palette = c("T2D" = "#321433", "0" = "lightgrey"))[["umap_plot"]]

hd_auto_umap(obj_igt_filtered, plot_color = "T2D", plot_palette = c("T2D" = "#321433", "0" = "lightgrey"))[["umap_plot"]]
```

### Glucose Groups

```{r}
glucosegroup_palette <- c("NGT_lowFINDRISC" = "#ffdddd",
                          "NGT_highFINDRISC" = "#d6cace",
                          "IFG" = "#ac98a2",
                          "IGT" = "#836879", 
                          "CGI" = "#5a3c54",
                          "T2D_new" = "#321433")

glucosegroup_features <- glucosegroup_model_results$features |> 
  top_n(20, wt = Scaled_Importance) |> 
  pull(Variable)

do_umap(data_igt |> select(-Sex, -Smoke_status, -all_of(disease_vec)),
        metadata |> mutate(glucose.group = factor(glucose.group)),
        color = "glucose.group",
        palette = glucosegroup_palette)

do_umap(data_igt |> select(DAid, any_of(glucosegroup_features), -Sex, -Smoke_status),
        metadata |> mutate(glucose.group = factor(glucose.group)),
        color = "glucose.group",
        palette = glucosegroup_palette)
```

### Obesity

```{r}
hd_auto_umap(obj_igt, plot_color = "Obesity", plot_palette = c("Obesity" = "#E7662B", "0" = "lightgrey"))[["umap_plot"]]

hd_auto_umap(obj_igt_filtered, plot_color = "Obesity", plot_palette = c("Obesity" = "#E7662B", "0" = "lightgrey"))[["umap_plot"]]
```

### MS

```{r}
hd_auto_umap(obj_igt, plot_color = "MS", plot_palette = c("MS" = "#08585A", "0" = "lightgrey"))[["umap_plot"]]

hd_auto_umap(obj_igt_filtered, plot_color = "MS", plot_palette = c("MS" = "#08585A", "0" = "lightgrey"))[["umap_plot"]]
```

### MASLD

```{r}
hd_auto_umap(obj_igt, plot_color = "MASLD", plot_palette = c("MASLD" = "#FFD321", "0" = "lightgrey"))[["umap_plot"]]

hd_auto_umap(obj_igt_filtered, plot_color = "MASLD", plot_palette = c("MASLD" = "#FFD321", "0" = "lightgrey"))[["umap_plot"]]
```

### CAC

```{r}
hd_auto_umap(obj_igt, plot_color = "CAC", plot_palette = c("CAC" = "#9E0142", "0" = "lightgrey"))[["umap_plot"]]

hd_auto_umap(obj_igt_filtered, plot_color = "CAC", plot_palette = c("CAC" = "#9E0142", "0" = "lightgrey"))[["umap_plot"]]
```

### Carotid Plaque

```{r}
hd_auto_umap(obj_igt, plot_color = "Carotid_plaque", plot_palette = c("Carotid_plaque" = "#E8A29A", "0" = "lightgrey"))[["umap_plot"]]

hd_auto_umap(obj_igt_filtered, plot_color = "Carotid_plaque", plot_palette = c("Carotid_plaque" = "#E8A29A", "0" = "lightgrey"))[["umap_plot"]]
```
